language: ruby
sudo: false
group: stable
cache: bundler
addons:
  postgresql: '9.3'
  apt:
    packages:
      - libpcap-dev
      - graphviz
language: ruby
rvm:
  - 2.2

node_js: 
  - "5"

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - rake --version

before_script:
  - bundle exec rake --version
  - bundle exec rake db:create
  - bundle exec rake db:migrate

install:
  - bundle install --path vendor/bundle

script:
  - bundle update
  - bundle update rake
  - bundle install
  - bundle exec rake db:migrate
