language: ruby
sudo: false
group: stable
cache: bundler
addons:
  postgresql: '9.3'
  apt:
    packages:
      - libpcap-dev
      - graphviz
language: ruby
rvm:
  - 2.2

node_js: 
  - "5"

before_install:
   - rake --version

install:
  - bundle install --path vendor/bundle

script:
  - bundle update
  - bundle install
  - bundle exec rake build
  - bundle exec rake builddoc
  - rake db:migrate
